// Hello Teddy 洪恩幼儿英语 视频清单（48 集）
// 视频文件位置：english/01.mp4 ~ 48.mp4
// 转码命令示例：ffmpeg -i "Hello Teddy洪恩幼儿英语（升级版）1.flv" -c:v libx264 -c:a aac -movflags +faststart "01.mp4"
window.ENGLISH_VIDEOS = [
  {id:'01', title:'Lesson 1', topic:'打招呼 Hello'},
  {id:'02', title:'Lesson 2', topic:'我是 I am'},
  {id:'03', title:'Lesson 3', topic:'数字 1-5'},
  {id:'04', title:'Lesson 4', topic:'颜色 Colors'},
  {id:'05', title:'Lesson 5', topic:'家人 Family'},
  {id:'06', title:'Lesson 6', topic:'身体 Body'},
  {id:'07', title:'Lesson 7', topic:'动物 Animals'},
  {id:'08', title:'Lesson 8', topic:'水果 Fruits'},
  {id:'09', title:'Lesson 9', topic:'食物 Food'},
  {id:'10', title:'Lesson 10', topic:'交通 Transport'},
  {id:'11', title:'Lesson 11', topic:'玩具 Toys'},
  {id:'12', title:'Lesson 12', topic:'衣服 Clothes'},
  {id:'13', title:'Lesson 13', topic:'天气 Weather'},
  {id:'14', title:'Lesson 14', topic:'季节 Seasons'},
  {id:'15', title:'Lesson 15', topic:'数字 6-10'},
  {id:'16', title:'Lesson 16', topic:'形状 Shapes'},
  {id:'17', title:'Lesson 17', topic:'房间 Rooms'},
  {id:'18', title:'Lesson 18', topic:'家具 Furniture'},
  {id:'19', title:'Lesson 19', topic:'蔬菜 Vegetables'},
  {id:'20', title:'Lesson 20', topic:'职业 Jobs'},
  {id:'21', title:'Lesson 21', topic:'方位 Where'},
  {id:'22', title:'Lesson 22', topic:'感觉 Feelings'},
  {id:'23', title:'Lesson 23', topic:'动作 Actions'},
  {id:'24', title:'Lesson 24', topic:'公园 Park'},
  {id:'25', title:'Lesson 25', topic:'学校 School'},
  {id:'26', title:'Lesson 26', topic:'文具 Stationery'},
  {id:'27', title:'Lesson 27', topic:'星期 Days'},
  {id:'28', title:'Lesson 28', topic:'月份 Months'},
  {id:'29', title:'Lesson 29', topic:'生日 Birthday'},
  {id:'30', title:'Lesson 30', topic:'节日 Festival'},
  {id:'31', title:'Lesson 31', topic:'饮料 Drinks'},
  {id:'32', title:'Lesson 32', topic:'早餐 Breakfast'},
  {id:'33', title:'Lesson 33', topic:'午餐 Lunch'},
  {id:'34', title:'Lesson 34', topic:'晚餐 Dinner'},
  {id:'35', title:'Lesson 35', topic:'昆虫 Insects'},
  {id:'36', title:'Lesson 36', topic:'海洋 Ocean'},
  {id:'37', title:'Lesson 37', topic:'天空 Sky'},
  {id:'38', title:'Lesson 38', topic:'植物 Plants'},
  {id:'39', title:'Lesson 39', topic:'体育 Sports'},
  {id:'40', title:'Lesson 40', topic:'乐器 Music'},
  {id:'41', title:'Lesson 41', topic:'问候 Greetings'},
  {id:'42', title:'Lesson 42', topic:'时间 Time'},
  {id:'43', title:'Lesson 43', topic:'问路 Direction'},
  {id:'44', title:'Lesson 44', topic:'购物 Shopping'},
  {id:'45', title:'Lesson 45', topic:'医院 Hospital'},
  {id:'46', title:'Lesson 46', topic:'安全 Safety'},
  {id:'47', title:'Lesson 47', topic:'游戏 Games'},
  {id:'48', title:'Lesson 48', topic:'再见 Goodbye'},
];
